### ISSUE TITLE
handling booloption(s)

### ISSUE THREAD

**Issue by BenjaminGTACoder** [E66666666/GTAVMenuExample#3]
hey ikt!
i am still using your menu base every day, i love so much. sorry to keep bothering, i hope you don't mind. i am having an issue with booloption which is hurting my performance because i have a stupidly low end pc.
i handle a bool like god mode, like this:
`dogodmode ? godmode(1) : godmode(0);`
obviously, not the best way to do this, i look at menyoo base a bit back, it seems to have a good way to handle this. but i HATE the menyoo base hahaha

do you have any advice for me to handle the bool better?
thank you, 
Benjamin

**Comment by ikt32** [comment]
Please give more context, I'm not sure what you're trying to do here.

**Comment by BenjaminGTACoder** [comment]
sorry, i would like to toggle god mode (for example) without turning it on/off every tick with this check:
`dogodmode ? godmode(1) : godmode(0);`

**Comment by ikt32** [comment]
This problem isn't related to this library.

You could toggle a boolean by using doing something like this:
```cpp
myMenu.BoolOption("Toggleable", myBooleanVariable, { "This will be toggled when this option is chosen." });
```

I suggest you go to GTAForums or the GTA5-Mods forums and ask there.

**Comment by BenjaminGTACoder** [comment]
sorry, i don't think we are understanding each other 

i want to call something when a bool is JUST disabled/JUST enabled, so it would only happen ONCE. how can i do this with gtavmenubase?

**Comment by ikt32** [comment]
```cpp
if (myMenu.BoolOption("Toggleable", myBooleanVariable, { "This will be toggled when this option is chosen." })) {
	if (bool) doSomething();
	else doSomethingElse();
}
```
? Read the comment above it, the function itself returns true on pressing accept (enter), and inside this block you can check the new value.

**Comment by BenjaminGTACoder** [comment]
it's good, but is not a prettier way to do this?

**Comment by ikt32** [comment]
Prettier? I can do the whole class-based approach but that'd require a full rewrite and events are a bitch in cpp.
